name: custom_signin_buttons
description: A package designed to create sign in buttons in an easier and more customizable way.
version: 1.0.2
repository: https://github.com/DarkHachi/custom_signin_buttons

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/playstore.png
    - assets/tiktok.png